// Generated by Selenium IDE

// 1 - Imports, Dependencias, Apontamentos de bibliotecas...
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;

// 2 - Classe - Guardar Informações...
public class CompradePassagemTest {

  // 2.1 - Atributos, Variáveis, Paramêtros, Características...
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  // 2.2 - Funções & Métodos
  // @ - Anotação
  @BeforeEach
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void compradepassagem() {
    driver.get("https://www.blazedemo.com/");
    driver.manage().window().setSize(new Dimension(1536, 816));
    driver.findElement(By.name("fromPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("fromPort"));
      dropdown.findElement(By.xpath("//option[. = 'São Paolo']")).click();
    }
    driver.findElement(By.name("toPort")).click();
    {
      WebElement dropdown = driver.findElement(By.name("toPort"));
      dropdown.findElement(By.xpath("//option[. = 'Berlin']")).click();
    }
    driver.findElement(By.cssSelector(".btn-primary")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("tr:nth-child(1) .btn"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("inputName")).click();
    driver.findElement(By.id("inputName")).sendKeys("David");
    driver.findElement(By.id("address")).sendKeys("123");
    driver.findElement(By.id("city")).sendKeys("123");
    driver.findElement(By.id("state")).sendKeys("123");
    driver.findElement(By.id("zipCode")).sendKeys("123");
    driver.findElement(By.id("cardType")).click();
    driver.findElement(By.id("creditCardNumber")).click();
    driver.findElement(By.id("creditCardNumber")).sendKeys("123");
    driver.findElement(By.id("rememberMe")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertEquals(driver.findElement(By.cssSelector("h1")).getText(), "Thank you for your purchase today!");
    assertEquals(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2)")).getText(), "555 USD");
  }
}